COMPLETES - 237: Added mock server config and basic test
openMF/ph-ee-connector-integration-test pull request #25
Opened 2023-03-16 09:54 UTC by danishjamal104

Addresses [PHEE-237](https://fynarfin.atlassian.net/jira/software/c/projects/PHEE/issues/PHEE-237)

Changes in this PR
1. Move all the step def into dedicated `stepdef` package.
2. New `mock-server` dependency and its basic setup.
3. Added test case to make sure previous application context is not broken.
4. Added test case to make sure mockServer injection and configuration works as expected.

2023-03-16 09:55 UTC, danishjamal104 commented
@fynmanoj please review and merge. Thanks :)

2023-03-16 15:05 UTC, fynmanoj requested changes
Design document required.
clarification needed. What is the lifecycle of the mock server? When does the mock server start and when does it end. Is it per testcase basis?
How to use the mock server for other use cases?

2023-03-16 17:20 UTC, danishjamal104 commented
> Design document required. clarification needed. What is the lifecycle of the mock server? When does the mock server start and when does it end. Is it per testcase basis? How to use the mock server for other use cases?

In the last meeting I brought up this but no one told me to work on design doc for this. I am then de scoping my sprint goal then. Ill be working on writing design doc for this type of test coverage.

2023-03-17 08:05 UTC, danishjamal104 commented
> Design document required. clarification needed. What is the lifecycle of the mock server? When does the mock server start and when does it end. Is it per testcase basis? How to use the mock server for other use cases?

https://docs.google.com/document/d/1qV6QP76tRaW6GYWFA0aZ7Oc1CH6brNQlrVL8vysUTcw/edit?usp=sharing

2023-03-21 11:36 UTC, merged