Inbound transfer API integration test added
openMF/ph-ee-connector-integration-test pull request #3
Opened 2022-11-17 01:28 UTC by danishjamal104

Updates in this PR
1. New test case for inbound transfer API or `/channel/transfer` endpoint.
2. Added new config named `ChannelConnectorConfig.java`, for the configurations like contactpoint and endpoints related to channel connector. 

### Another PR needed to be reviewed and merged before this PR: https://github.com/openMF/ph-ee-connector-integration-test/pull/2

2022-12-13 13:16 UTC, fynmanoj requested changes

2022-12-13 13:16 UTC, fynmanoj commented on build.gradle
> +		url = uri('https://fynarfin.jfrog.io/artifactory/fyn-libs-snapshot-local/')
is this publically open to reading?

2022-12-13 13:16 UTC, fynmanoj commented on src/test/java/org/mifos/integrationtest/cucumber/InboundStepDef.java
> +                .body(mockTransactionChannelRequestDTO) // todo check if this is correct?
is that TODO done?  remove comment

2022-12-13 13:21 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/InboundStepDef.java
> +                .body(mockTransactionChannelRequestDTO) // todo check if this is correct?
yes its done

2022-12-13 13:21 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/InboundStepDef.java
> +        logger.info("Inbound transfer Response: " + BaseStepDef.response);
ok

2022-12-13 13:22 UTC, danishjamal104 commented on build.gradle
> +		url = uri('https://fynarfin.jfrog.io/artifactory/fyn-libs-snapshot-local/')
I am not aware of

2022-12-14 06:01 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/InboundStepDef.java
> +        logger.info("Inbound transfer Response: " + BaseStepDef.response);
done

2022-12-14 06:01 UTC, danishjamal104 commented on src/test/java/org/mifos/integrationtest/cucumber/InboundStepDef.java
> +        String json = "{\n" +
updated

2022-12-14 10:32 UTC, danishjamal104 commented on build.gradle
> +		url = uri('https://fynarfin.jfrog.io/artifactory/fyn-libs-snapshot-local/')
I think yes

2022-12-14 14:01 UTC, fynmanoj requested changes
can you remove cucumber report from the code

2022-12-14 16:26 UTC, danishjamal104 commented
> can you remove cucumber report from the code

done

2022-12-14 16:29 UTC, fynmanoj approved these changes

2022-12-14 16:36 UTC, merged